package com.tylink.create;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.tylink.create.model.CreateUrlRequest;
import com.tylink.create.model.ShortUrl;
import com.tylink.create.model.Visibility;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.dynamodb.model.PutItemRequest;
import software.amazon.awssdk.utils.StringUtils;
import software.amazon.lambda.powertools.logging.Logging;

import java.security.SecureRandom;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

public class CreateUrlHandler implements RequestHandler<APIGatewayV2HTTPEvent, APIGatewayV2HTTPResponse> {

    private static final Logger log = LogManager.getLogger(CreateUrlHandler.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final String BASE62_ALPHABET =
            "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    private static final int SHORT_CODE_LENGTH = 7;
    private static final SecureRandom RANDOM = new SecureRandom();

    private final DynamoDbClient dynamoDb;
    private final String tableName;

    public CreateUrlHandler() {
        this(DynamoDbClient.create(), System.getenv("TABLE_NAME"));
    }

    CreateUrlHandler(DynamoDbClient dynamoDb, String tableName) {
        this.dynamoDb = dynamoDb;
        this.tableName = tableName;
    }

    @Logging(logEvent = true)
    @Override
    public APIGatewayV2HTTPResponse handleRequest(APIGatewayV2HTTPEvent input, Context context) {
        log.info("Event: {}", input);
        Optional<CreateUrlRequest> request = parseBody(input.getBody());
        if (request.isEmpty()) {
            log.error("Request body is empty!");
            return jsonResponse(400, Map.of("message", "invalid request body"));
        }
        if (StringUtils.isBlank(request.get().longUrl)) {
            log.error("Original URL is empty!");
            return jsonResponse(400, Map.of("message", "longUrl is required"));
        }

        Optional<Visibility> visibility = Visibility.parse(request.get().visibility);
        if (visibility.isEmpty()) {
            log.error("Visibility: {} is invalid!");
            return jsonResponse(400, Map.of("message", "visibility must be PUBLIC or PRIVATE"));
        }

        // PUBLIC never requires auth (anonymous callers are allowed); PRIVATE does,
        // since its ownership check (F8) needs a real ownerId to compare against later.
        Optional<String> ownerId = extractOwnerId(input);
        log.info("ownerId: {}", ownerId);
        if (visibility.get() == Visibility.PRIVATE && ownerId.isEmpty()) {
            log.warn("Rejected create URL request: PRIVATE visibility requires an authenticated caller");
            return jsonResponse(401, Map.of("message", "unauthorized"));
        }

        return createUrl(request.get().longUrl, ownerId, visibility.get());
    }

    private APIGatewayV2HTTPResponse createUrl(String longUrl, Optional<String> ownerId, Visibility visibility) {
        ShortUrl shortUrl = ShortUrl.create(generateShortCode(), longUrl, ownerId.orElse(null), visibility);
        dynamoDb.putItem(PutItemRequest.builder()
                .tableName(tableName)
                .item(shortUrl.toItem())
                .build());

        log.info("Created shortCode={} visibility={} anonymous={}", shortUrl.shortCode(), visibility, ownerId.isEmpty());
        return jsonResponse(201, Map.of("shortCode", shortUrl.shortCode(), "visibility", visibility.name()));
    }

    private Optional<CreateUrlRequest> parseBody(String body) {
        if (StringUtils.isBlank(body)) {
            return Optional.empty();
        }
        try {
            return Optional.of(MAPPER.readValue(body, CreateUrlRequest.class));
        } catch (JsonProcessingException e) {
            log.warn("Rejected create URL request: malformed body");
            return Optional.empty();
        }
    }

    private Optional<String> extractOwnerId(APIGatewayV2HTTPEvent input) {
        // ownerId is userId generated by custom authorizer to support pubic access
        return Optional.ofNullable(input.getRequestContext())
                .map(APIGatewayV2HTTPEvent.RequestContext::getAuthorizer)
                .map(APIGatewayV2HTTPEvent.RequestContext.Authorizer::getLambda)
                .map(context -> context.get("ownerId"))
                .map(Object::toString)
                .filter(StringUtils::isNotBlank);
    }

    private String generateShortCode() {
        return RANDOM.ints(SHORT_CODE_LENGTH, 0, BASE62_ALPHABET.length())
                .mapToObj(BASE62_ALPHABET::charAt)
                .map(String::valueOf)
                .collect(Collectors.joining());
    }

    private APIGatewayV2HTTPResponse jsonResponse(int statusCode, Map<String, String> body) {
        try {
            return APIGatewayV2HTTPResponse.builder()
                    .withStatusCode(statusCode)
                    .withHeaders(Map.of("Content-Type", "application/json"))
                    .withBody(MAPPER.writeValueAsString(body))
                    .build();
        } catch (JsonProcessingException e) {
            log.error("Failed to serialize response body, falling back to 500", e);
            return APIGatewayV2HTTPResponse.builder()
                    .withStatusCode(500)
                    .withHeaders(Map.of("Content-Type", "application/json"))
                    .withBody("{\"message\":\"internal server error\"}")
                    .build();
        }
    }
}
